#!/bin/bash -e

if [[ $UID == 0 ]]; then
  echo "Script must not be run as root"
  exit 1
fi

if [ $# != 1 ]; then
  echo "usage: $0 [Debug/Release/...]"
  exit 1
fi

# MINGW64_NT-???, Darwin, Linux
OS=$(uname)

# GitHub Actions uses Ubuntu, needs gcc>=8
if [[ $(uname -a) =~ "Ubuntu" ]]; then
  export CC="gcc-8"
  export CXX="g++-8"
fi

case "$OS" in
"Linux" | "Darwin")
  cmake --build build --config "$1" -- --no-print-directory
  ;;
*)
  cmake --build build --config "$1"
  ;;
esac
